### PR TITLE
Log errors parsing JSON

### PR DESCRIPTION
**Pull request by w43l**

### CODE REVIEW

**Comment by jpodwys** [comment]
People can use this module to cache data that is not JSON. The module attempts to JSON.parse retrieved data as a convenience. If I were to merge this PR, the module would log errors both when parsing JSON as JSON fails (which is good) and when parsing non-JSON as JSON fails (which is bad). 

The catch statement in this part of the code is intended to signify that the data retrieved from the cache is not JSON and should therefore be returned as is. 

Can you please explain the use case that makes this change necessary? If the logging would indeed help, we can make it an opt-in experience so people caching non-JSON data don't get false error reports.

**Comment by w43l** [comment]
What you're saying makes sense, if the data being cached is not JSON it doesn't make sense to display errors parsing it.

I opened this PR because I'm using this package and I had a case where the cache was not being populated and I suspected it was because there was an error parsing the JSON.

I think an opt-in approach makes sense here, since if you're caching JSON data you'd want to know when/if JSON parsing fails

**Comment by jpodwys** [comment]
Perfect. If you'd like to update your PR so the constructor's `config` argument accepts a `logJsonParseFailures` boolean that defaults to false,  that would be great. Then you could wrap your log statement as follows:

``` javascript
if(self.logJsonParseFailures){
  log(true, 'error converting to JSON, err:', err);
}
```

**Comment by w43l** [comment]
@jpodwys Check now please

**Comment by jpodwys** [comment]
Published to NPM in `1.2.0`.

**Pull request merged**
